filter:
  vertical_zones: [
            {'start': 0.0, 'end': 0.25, 'downsample': 4},  # Upper 25% of rows, keep 1/4
            {'start': 0.25, 'end': 0.75, 'downsample': 1},  # Middle 50%, keep all
            {'start': 0.75, 'end': 1.0, 'downsample': 4},  # Lower 25%, keep 1/4
        ]
vehicle:
  abs_pose: [-2.4, 0, 0, 0, 0, -0.7]  #absolute position and rotation
  linear_speed_f: 0.5
lidar:
  pose: [0.26, 0, 0.475, 0, -0.1570796, 0]  #lidar position and rotation relative to the car
  hz: 20
  h_samples: 500
  h_min_angle: 2.356194   #135째
  h_max_angle: 3.926991   #225째
  h_resolution: 0.1
  v_samples: 128
  v_min_angle: -0.3926991 #-22.5째
  v_max_angle: 0.3926991  #22.5째
  v_resolution: 0.1
  min_range: 0.01
  max_range: 80.0
  range_resolution: 0.01
  noise_mean: 0.0
  noise_std: 0.05
cones:
  min_dist: 1.5 #minimum distance between cones
  scale: 10 #map coordinates scale
  track_width: 3
